version: "3"
services:
  mysql_db:
    container_name: mysql-container
    image: mysql:5.7
    environment:
     MYSQL_ROOT_PASSWORD: 'senha-mysql'
    ports:
      # Garanta que não haverá conflitos de porta com um banco que esteja
      # rodando localmente
      - 3306:3306